import "dotenv/config";
import { PrismaClient, Prisma, Role, ThemeStatus } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import type { ThemeConfig } from "../src/lib/themes/types";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

async function main() {
  const admin = await prisma.user.upsert({
    where: { phone: "+966500000001" },
    update: {},
    create: {
      phone: "+966500000001",
      name: "مدير دعوتي",
      role: Role.ADMIN,
      phoneVerifiedAt: new Date(),
    },
  });

  const gateUser = await prisma.user.upsert({
    where: { phone: "+966500000002" },
    update: {},
    create: {
      phone: "+966500000002",
      name: "موظف البوابة",
      role: Role.GATE_STAFF,
      phoneVerifiedAt: new Date(),
    },
  });

  await prisma.gateStaff.upsert({
    where: { userId: gateUser.id },
    update: {},
    create: { userId: gateUser.id, name: gateUser.name, phone: gateUser.phone },
  });

  const plans = [
    { name: "Starter", nameAr: "الأساسية", invitationCount: 50, price: 299, sortOrder: 1 },
    { name: "Signature", nameAr: "المميزة", invitationCount: 150, price: 699, sortOrder: 2 },
    { name: "Grand", nameAr: "الفاخرة", invitationCount: 500, price: 1799, sortOrder: 3 },
  ];

  for (const plan of plans) {
    const existing = await prisma.plan.findFirst({ where: { nameAr: plan.nameAr } });
    if (existing) {
      await prisma.plan.update({ where: { id: existing.id }, data: plan });
    } else {
      await prisma.plan.create({ data: plan });
    }
  }

  const themes: Array<{
    slug: string;
    name: string;
    nameAr: string;
    category: string;
    config: ThemeConfig;
  }> = [
    {
      slug: "palace-gold",
      name: "Royal Palace",
      nameAr: "قصر ملكي",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: {
          bg: "#14110d",
          surface: "#1e1912",
          fg: "#f3ede3",
          fgMuted: "#b8ac9a",
          accent: "#d4af74",
          accentFg: "#14110d",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "arch-reveal", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        // Trial: floating hearts particles — only on this theme until approved for the rest.
        particles: { effect: "floating-hearts" },
      },
    },
    {
      slug: "modern-minimal",
      name: "Modern Minimal",
      nameAr: "مينيمال حديث",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#faf9f7",
          surface: "#ffffff",
          fg: "#161513",
          fgMuted: "#6f6a62",
          accent: "#161513",
          accentFg: "#ffffff",
        },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "botanical-garden",
      name: "Garden Estate",
      nameAr: "حديقة فاخرة",
      category: "botanical",
      config: {
        layout: "envelope-reveal",
        palette: {
          bg: "#f4f1e8",
          surface: "#fffdf7",
          fg: "#2b3327",
          fgMuted: "#6b7460",
          accent: "#5c6e4f",
          accentFg: "#ffffff",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "velvet-midnight",
      name: "Velvet Midnight",
      nameAr: "مخمل الليل",
      category: "luxury",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#0d1321",
          surface: "#16213a",
          fg: "#f0ece0",
          fgMuted: "#a8a49a",
          accent: "#cda86a",
          accentFg: "#0d1321",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "black-tie",
      name: "Black Tie",
      nameAr: "بلاك تاي",
      category: "dark",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#000000",
          surface: "#111111",
          fg: "#ffffff",
          fgMuted: "#9a9a9a",
          accent: "#ffffff",
          accentFg: "#000000",
        },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "desert-rose",
      name: "Desert Rose",
      nameAr: "وردة الصحراء",
      category: "saudi",
      config: {
        layout: "arch-frame",
        palette: {
          bg: "#f2e4d8",
          surface: "#fbf3ea",
          fg: "#4a2f22",
          fgMuted: "#8a6a54",
          accent: "#b5613f",
          accentFg: "#ffffff",
        },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "Tajawal", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "najdi-modern",
      name: "Modern Najdi",
      nameAr: "نجدي حديث",
      category: "saudi",
      config: {
        layout: "split-portrait",
        palette: {
          bg: "#efe9df",
          surface: "#ffffff",
          fg: "#262220",
          fgMuted: "#6f6a63",
          accent: "#8a2f26",
          accentFg: "#ffffff",
        },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "Tajawal", latinDisplay: "Inter" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "dusty-rose-editorial",
      name: "Dusty Rose Editorial",
      nameAr: "إديتوريال وردي",
      category: "romantic",
      config: {
        layout: "split-portrait",
        palette: {
          bg: "#f7eeec",
          surface: "#fffaf9",
          fg: "#4a2f30",
          fgMuted: "#9c7a78",
          accent: "#c98a86",
          accentFg: "#ffffff",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "pearl-luster",
      name: "Pearl Luster",
      nameAr: "لؤلؤة فاخرة",
      category: "luxury",
      config: {
        layout: "envelope-reveal",
        palette: {
          bg: "#f5f3f0",
          surface: "#ffffff",
          fg: "#15130f",
          fgMuted: "#6b6560",
          accent: "#b8a99a",
          accentFg: "#15130f",
        },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "royal-espresso",
      name: "Royal Espresso",
      nameAr: "إسبريسو ملكي",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: {
          bg: "#2a1c14",
          surface: "#3a2818",
          fg: "#f0e6da",
          fgMuted: "#b5a692",
          accent: "#c9a15c",
          accentFg: "#2a1c14",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Minimalist Series ---
    {
      slug: "pure-ivory",
      name: "Pure Ivory",
      nameAr: "عاج نقي",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#faf8f4", surface: "#ffffff", fg: "#1a1a1a", fgMuted: "#8a8580", accent: "#c2a878", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "the-line",
      name: "The Line",
      nameAr: "الخط",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#fefdfb", surface: "#ffffff", fg: "#232323", fgMuted: "#999188", accent: "#cba135", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "ghost-monogram",
      name: "Ghost Monogram",
      nameAr: "مونوغرام شبحي",
      category: "minimal",
      config: {
        layout: "split-portrait",
        palette: { bg: "#f6f5f2", surface: "#ffffff", fg: "#232323", fgMuted: "#b8b4ac", accent: "#d8d3c8", accentFg: "#232323" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "Tajawal", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "architectural-grid",
      name: "Architectural Grid",
      nameAr: "شبكة معمارية",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#f4f4f2", surface: "#ffffff", fg: "#2b2f33", fgMuted: "#8d9399", accent: "#6b7280", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "stone-serif",
      name: "Stone & Serif",
      nameAr: "حجر وسيريف",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#e8e5df", surface: "#f2f0eb", fg: "#33302a", fgMuted: "#837c70", accent: "#7a6f5e", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "centered-soul",
      name: "Centered Soul",
      nameAr: "روح متمركزة",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#ffffff", surface: "#faf9f7", fg: "#1c1c1c", fgMuted: "#9a9a9a", accent: "#b08d57", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "the-frame",
      name: "The Frame",
      nameAr: "الإطار",
      category: "minimal",
      config: {
        layout: "arch-frame",
        palette: { bg: "#ffffff", surface: "#fdfdfc", fg: "#1f1f1f", fgMuted: "#9c9c9c", accent: "#1f1f1f", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "floating-names",
      name: "Floating Names",
      nameAr: "أسماء عائمة",
      category: "minimal",
      config: {
        layout: "split-portrait",
        palette: { bg: "#fbfaf8", surface: "#ffffff", fg: "#141414", fgMuted: "#9d9d9d", accent: "#141414", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "paper-press",
      name: "Paper Press",
      nameAr: "بصمة الورق",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#f3efe6", surface: "#faf7f0", fg: "#3a352c", fgMuted: "#8f8676", accent: "#a6987c", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "quiet-luxury",
      name: "Quiet Luxury",
      nameAr: "فخامة هادئة",
      category: "minimal",
      config: {
        layout: "classic-center",
        palette: { bg: "#ddd4c4", surface: "#e8e1d3", fg: "#3a3226", fgMuted: "#6b5f4a", accent: "#8a7452", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- High Luxury & Royal ---
    {
      slug: "grand-ballroom",
      name: "Grand Ballroom",
      nameAr: "قاعة الرقص الكبرى",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: { bg: "#1a1408", surface: "#241c0f", fg: "#f5ecd8", fgMuted: "#b8a97e", accent: "#e8c468", accentFg: "#1a1408" },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "arch-reveal", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "palace-entrance",
      name: "Palace Entrance",
      nameAr: "مدخل القصر",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: { bg: "#efe9df", surface: "#ffffff", fg: "#2b2620", fgMuted: "#857c6c", accent: "#a68a5b", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "the-chandelier",
      name: "The Chandelier",
      nameAr: "الثريا",
      category: "luxury",
      config: {
        layout: "classic-center",
        palette: { bg: "#0f1116", surface: "#191c24", fg: "#f2f0eb", fgMuted: "#a6a9b3", accent: "#cfd4e0", accentFg: "#0f1116" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "silk-flow",
      name: "Silk Flow",
      nameAr: "انسياب الحرير",
      category: "luxury",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#f3ece1", surface: "#fbf6ee", fg: "#3c2f22", fgMuted: "#8f7a63", accent: "#c9a97a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "gilded-arch",
      name: "Gilded Arch",
      nameAr: "قوس مذهّب",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: { bg: "#12100d", surface: "#1c1915", fg: "#efe8da", fgMuted: "#a89d87", accent: "#d3b06a", accentFg: "#12100d" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "majestic-arch",
      name: "Majestic Arch",
      nameAr: "قوس مهيب",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: { bg: "#14110d", surface: "#201a12", fg: "#f3ede0", fgMuted: "#b5a98e", accent: "#b8925a", accentFg: "#14110d" },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "crowned-typo",
      name: "Crowned Typo",
      nameAr: "تاج الحروف",
      category: "luxury",
      config: {
        layout: "classic-center",
        palette: { bg: "#ffffff", surface: "#faf9f7", fg: "#14110d", fgMuted: "#8f8a80", accent: "#a68a5b", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Saudi & Gulf Inspired ---
    {
      slug: "riyadh-horizon",
      name: "Riyadh Horizon",
      nameAr: "أفق الرياض",
      category: "saudi",
      config: {
        layout: "split-portrait",
        palette: { bg: "#eef0ef", surface: "#ffffff", fg: "#1f2a28", fgMuted: "#6f7a77", accent: "#2f6f62", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "Tajawal", latinDisplay: "Inter" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "the-gateway",
      name: "The Gateway",
      nameAr: "البوابة",
      category: "saudi",
      config: {
        layout: "arch-frame",
        palette: { bg: "#2c2018", surface: "#392a1e", fg: "#f2e6d5", fgMuted: "#b3a189", accent: "#c08a4e", accentFg: "#2c2018" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "Tajawal", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "oasis-couture",
      name: "Oasis Couture",
      nameAr: "أناقة الواحة",
      category: "saudi",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#eef0e2", surface: "#f7f8ee", fg: "#3a3c28", fgMuted: "#7d8064", accent: "#8a9152", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "Tajawal", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Feminine & Romantic ---
    {
      slug: "soft-couture",
      name: "Soft Couture",
      nameAr: "أناقة ناعمة",
      category: "romantic",
      config: {
        layout: "split-portrait",
        palette: { bg: "#f6efe9", surface: "#fffbf8", fg: "#4a3831", fgMuted: "#a0897f", accent: "#cba594", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "botanical-fine-line",
      name: "Botanical Fine-Line",
      nameAr: "خطوط نباتية رفيعة",
      category: "romantic",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#f2f3ea", surface: "#fbfcf5", fg: "#2d3324", fgMuted: "#7c8468", accent: "#6f7d4f", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "petal-shadows",
      name: "Petal Shadows",
      nameAr: "ظلال البتلات",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: { bg: "#faf1ef", surface: "#fffafa", fg: "#4a3236", fgMuted: "#a58589", accent: "#d3a5ab", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "romantic-arch",
      name: "Romantic Arch",
      nameAr: "قوس رومانسي",
      category: "romantic",
      config: {
        layout: "arch-frame",
        palette: { bg: "#f7f0e8", surface: "#fffcf7", fg: "#4a3a2c", fgMuted: "#a08b74", accent: "#c9a06a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Dark & Evening ---
    {
      slug: "midnight-palace",
      name: "Midnight Palace",
      nameAr: "قصر منتصف الليل",
      category: "dark",
      config: {
        layout: "arch-frame",
        palette: { bg: "#17181a", surface: "#212325", fg: "#f0ece4", fgMuted: "#a6a19a", accent: "#e0a95c", accentFg: "#17181a" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "arch-reveal", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "burgundy-velvet",
      name: "Burgundy Velvet",
      nameAr: "مخمل عنابي",
      category: "dark",
      config: {
        layout: "classic-center",
        palette: { bg: "#2b0f14", surface: "#3a151c", fg: "#f3e6d8", fgMuted: "#c9a89a", accent: "#d4af74", accentFg: "#2b0f14" },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "smoked-glass",
      name: "Smoked Glass",
      nameAr: "زجاج مدخّن",
      category: "dark",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#16140f", surface: "#201d16", fg: "#e8e3d8", fgMuted: "#918c80", accent: "#6b6558", accentFg: "#e8e3d8" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "eclipse",
      name: "Eclipse",
      nameAr: "الكسوف",
      category: "dark",
      config: {
        layout: "classic-center",
        palette: { bg: "#000000", surface: "#0d0d0d", fg: "#ffffff", fgMuted: "#7a7a7a", accent: "#4a4a4a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Experimental & Modern ---
    {
      slug: "asymmetric-edge",
      name: "Asymmetric Edge",
      nameAr: "حافة غير متماثلة",
      category: "experimental",
      config: {
        layout: "split-portrait",
        palette: { bg: "#f5f3ee", surface: "#ffffff", fg: "#1a1a1a", fgMuted: "#8f8f8f", accent: "#c9a35a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "the-reveal",
      name: "The Reveal",
      nameAr: "الكشف",
      category: "experimental",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#efece5", surface: "#ffffff", fg: "#201d17", fgMuted: "#857e6f", accent: "#93876a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "Tajawal", latinDisplay: "Inter" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "geometric-play",
      name: "Geometric Play",
      nameAr: "لعب هندسي",
      category: "experimental",
      config: {
        layout: "split-portrait",
        palette: { bg: "#f2ede2", surface: "#ffffff", fg: "#262019", fgMuted: "#8a8172", accent: "#b5763f", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "gate-swing", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "typographic-hero",
      name: "Typographic Hero",
      nameAr: "بطل الطباعة",
      category: "experimental",
      config: {
        layout: "split-portrait",
        palette: { bg: "#ffffff", surface: "#f7f7f5", fg: "#0a0a0a", fgMuted: "#6e6e6e", accent: "#0a0a0a", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "seal-break", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "digital-horizon",
      name: "Digital Horizon",
      nameAr: "أفق رقمي",
      category: "experimental",
      config: {
        layout: "classic-center",
        palette: { bg: "#0d0f12", surface: "#15181c", fg: "#eef1f4", fgMuted: "#8b939c", accent: "#4fc3d9", accentFg: "#0d0f12" },
        fonts: { arabicDisplay: "Reem Kufi", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Inter" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    // --- Added from designd2/ reference mockups (2026-08-18), by explicit request ---
    {
      slug: "elite-couture",
      name: "Elite Couture",
      nameAr: "نخبة الأناقة",
      category: "luxury",
      config: {
        layout: "classic-center",
        palette: { bg: "#131313", surface: "#1b1b1b", fg: "#e5e2e1", fgMuted: "#959083", accent: "#d4c78f", accentFg: "#131313" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Bodoni Moda" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "secret-garden",
      name: "Secret Garden",
      nameAr: "الحديقة السرية",
      category: "botanical",
      config: {
        layout: "envelope-reveal",
        palette: { bg: "#fff9f0", surface: "#f9f3ea", fg: "#1d1b16", fgMuted: "#75786e", accent: "#526442", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "EB Garamond" },
        motion: { openStyle: "envelope", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "palace-doors",
      name: "The Palace Doors",
      nameAr: "أبواب القصر",
      category: "luxury",
      config: {
        layout: "arch-frame",
        palette: { bg: "#fef8f6", surface: "#f8f2f0", fg: "#1d1b1a", fgMuted: "#7e766f", accent: "#675f32", accentFg: "#ffffff" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "EB Garamond" },
        motion: { openStyle: "doors", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
      },
    },
    {
      slug: "immersive-espresso",
      name: "Immersive Espresso",
      nameAr: "التجربة الغامرة",
      category: "experimental",
      config: {
        layout: "classic-center",
        palette: { bg: "#19120e", surface: "#2e1a11", fg: "#f3ede3", fgMuted: "#b8ac9a", accent: "#e3bfb0", accentFg: "#19120e" },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Playfair Display" },
        motion: { openStyle: "curtain", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        background: { effect: "shader-silk" },
      },
    },
    // --- New standalone theme, from-scratch redesign (2026-08-20) ---
    {
      slug: "rose-candlelight",
      name: "Rose Candlelight",
      nameAr: "شموع الورد",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#571F24",
          surface: "#360B0B",
          fg: "#DCAEA8",
          fgMuted: "#E7C4BC",
          accent: "#BF8682",
          accentFg: "#360B0B",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss" },
        family: "rose-candlelight",
        colorTag: "عنابي",
      },
    },
    // --- Color variants of rose-candlelight — same art, hue-shifted (2026-08-20) ---
    {
      slug: "rose-navy",
      name: "Rose Navy",
      nameAr: "شموع الورد الكحلي",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#1F2B57",
          surface: "#0B1136",
          fg: "#A8A9DC",
          fgMuted: "#BEBCE7",
          accent: "#8286BF",
          accentFg: "#0B1136",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss", assetFolder: "rose-navy" },
        family: "rose-candlelight",
        colorTag: "كحلي",
      },
    },
    {
      slug: "rose-emerald",
      name: "Rose Emerald",
      nameAr: "شموع الورد الزمردي",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#1F573F",
          surface: "#0B3628",
          fg: "#A8DCD1",
          fgMuted: "#BCE7E1",
          accent: "#82BFAF",
          accentFg: "#0B3628",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss", assetFolder: "rose-emerald" },
        family: "rose-candlelight",
        colorTag: "أخضر",
      },
    },
    {
      slug: "rose-purple",
      name: "Rose Purple",
      nameAr: "شموع الورد البنفسجي",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#441F57",
          surface: "#2B0B36",
          fg: "#D5A8DC",
          fgMuted: "#E4BCE7",
          accent: "#B482BF",
          accentFg: "#2B0B36",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss", assetFolder: "rose-purple" },
        family: "rose-candlelight",
        colorTag: "بنفسجي",
      },
    },
    {
      slug: "rose-blush",
      name: "Rose Fuchsia",
      nameAr: "شموع الورد الفوشي",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#672141",
          surface: "#400A1E",
          fg: "#FFC0D0",
          fgMuted: "#FFCDD6",
          accent: "#E196AD",
          accentFg: "#400A1E",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss", assetFolder: "rose-blush" },
        family: "rose-candlelight",
        colorTag: "وردي",
      },
    },
    {
      slug: "rose-charcoal",
      name: "Rose Charcoal & Gold",
      nameAr: "شموع الورد الأسود الذهبي",
      category: "romantic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#363232",
          surface: "#211E1E",
          fg: "#E8DFD3",
          fgMuted: "#C9BFB0",
          accent: "#C9A66B",
          accentFg: "#211E1E",
        },
        fonts: { arabicDisplay: "Aref Ruqaa", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "rose-emboss", assetFolder: "rose-charcoal" },
        family: "rose-candlelight",
        colorTag: "أسود",
      },
    },
    // --- New design (2026-08-21): illustrated ivory bride, floral arch card ---
    {
      slug: "ivory-bloom",
      name: "Ivory Bloom",
      nameAr: "عروس الياسمين",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F5F1EA",
          surface: "#FBF8F3",
          fg: "#3A332B",
          fgMuted: "#8A7F6E",
          accent: "#B9A97E",
          accentFg: "#3A332B",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: { style: "bridal-frame", assetFolder: "ivory-bloom" },
        family: "ivory-bloom",
        colorTag: "بيج",
      },
    },
    // --- Color variants of ivory-bloom — same art, selectively recolored (2026-08-21) ---
    {
      slug: "ivory-bloom-rose",
      name: "Ivory Bloom Rose",
      nameAr: "عروس الياسمين الوردي",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#FBF3F1",
          surface: "#FDF8F7",
          fg: "#3A2E30",
          fgMuted: "#8A7278",
          accent: "#B5647A",
          accentFg: "#FBF3F1",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-rose",
          layout: {
            closedAspect: "1182/727",
            sealPosition: { left: "50.1%", top: "59.4%" },
            openTextZone: { insetX: "16.2%", top: "22.3%", bottom: "31.7%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "37.4%", width: "26.5%", top: "78.7%", height: "11.6%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "وردي",
      },
    },
    {
      slug: "ivory-bloom-sage",
      name: "Ivory Bloom Sage",
      nameAr: "عروس الياسمين الأخضر",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F3EFE2",
          surface: "#F8F5EC",
          fg: "#332F22",
          fgMuted: "#8A8268",
          accent: "#C6A968",
          accentFg: "#332F22",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-sage",
          layout: {
            closedAspect: "1169/731",
            sealPosition: { left: "50.5%", top: "57.6%" },
            openTextZone: { insetX: "17.8%", top: "22.4%", bottom: "30.8%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "38.4%", width: "25.2%", top: "80.5%", height: "11.7%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "أخضر",
      },
    },
    {
      slug: "ivory-bloom-sand",
      name: "Ivory Bloom Sand",
      nameAr: "عروس الياسمين البيج",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F7F1E6",
          surface: "#FBF7EE",
          fg: "#362E22",
          fgMuted: "#8C7C5E",
          accent: "#A8824A",
          accentFg: "#F7F1E6",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-sand",
          layout: {
            closedAspect: "1200/727",
            sealPosition: { left: "50%", top: "62.9%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "38.4%", width: "25.2%", top: "80.5%", height: "12.1%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "بيج",
      },
    },
    {
      slug: "ivory-bloom-mauve",
      name: "Ivory Bloom Mauve",
      nameAr: "عروس الياسمين البنفسجي",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F5EEF1",
          surface: "#FAF5F7",
          fg: "#332A30",
          fgMuted: "#85717C",
          accent: "#8A5C72",
          accentFg: "#F5EEF1",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-mauve",
          layout: {
            closedAspect: "1170/695",
            sealPosition: { left: "50.1%", top: "57.2%" },
            openTextZone: { insetX: "19.8%", top: "28%", bottom: "27%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "38.4%", width: "25.2%", top: "80.5%", height: "11.7%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "بنفسجي",
      },
    },
    {
      slug: "ivory-bloom-sky",
      name: "Ivory Bloom Sky",
      nameAr: "عروس الياسمين السماوي",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#EFF4F7",
          surface: "#F6FAFB",
          fg: "#28323A",
          fgMuted: "#71838F",
          accent: "#9FADB8",
          accentFg: "#28323A",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-sky",
          layout: {
            closedAspect: "1167/643",
            sealPosition: { left: "50.7%", top: "56.7%" },
            openTextZone: { insetX: "18.7%", top: "22.4%", bottom: "31.9%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "38.4%", width: "25.2%", top: "80.5%", height: "11.7%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "أزرق",
      },
    },
    {
      slug: "ivory-bloom-navy",
      name: "Ivory Bloom Navy",
      nameAr: "عروس الياسمين الكحلي",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F3F1EA",
          surface: "#F8F6F0",
          fg: "#22283A",
          fgMuted: "#6B7488",
          accent: "#C9A66B",
          accentFg: "#1F2B4D",
          swatch: "#1F2B4D",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-navy",
          layout: {
            closedAspect: "1158/656",
            sealPosition: { left: "50.3%", top: "60%" },
            openTextZone: { insetX: "21.9%", top: "25.1%", bottom: "34.7%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "39%", width: "20%", top: "77.4%", height: "12.6%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "كحلي",
      },
    },
    {
      slug: "ivory-bloom-burgundy",
      name: "Ivory Bloom Burgundy",
      nameAr: "عروس الياسمين العنابي",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F7F1E8",
          surface: "#FBF7EF",
          fg: "#3A1E22",
          fgMuted: "#8C7268",
          accent: "#C9A66B",
          accentFg: "#4A1620",
          swatch: "#6B1B29",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-burgundy",
          layout: {
            closedAspect: "1167/694",
            sealPosition: { left: "50.5%", top: "58%" },
            openTextZone: { insetX: "21.6%", top: "24.7%", bottom: "34.6%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "40%", width: "19%", top: "76.9%", height: "11.3%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "عنابي",
      },
    },
    {
      slug: "ivory-bloom-mocha",
      name: "Ivory Bloom Mocha",
      nameAr: "عروس الياسمين الموكا",
      category: "classic",
      config: {
        layout: "classic-center",
        palette: {
          bg: "#F3ECDE",
          surface: "#F8F3E9",
          fg: "#3A2E1E",
          fgMuted: "#8C7B5E",
          accent: "#B8935A",
          accentFg: "#3A2416",
          swatch: "#6B4A2E",
        },
        fonts: { arabicDisplay: "Amiri", arabicBody: "IBM Plex Sans Arabic", latinDisplay: "Cormorant Garamond" },
        motion: { openStyle: "fade", reducedMotionFallback: "fade" },
        sections: { showCountdown: true, showMap: true, showRsvp: true },
        card: {
          style: "bridal-frame",
          assetFolder: "ivory-bloom-mocha",
          layout: {
            closedAspect: "1167/746",
            sealPosition: { left: "50%", top: "60.1%" },
            openTextZone: { insetX: "21.6%", top: "25.4%", bottom: "33.9%" },
            pass: { textTop: "23%", iconsTop: "43%", qr: { left: "48%", width: "28%", top: "58%", height: "14%" } },
          },
        },
        family: "ivory-bloom",
        colorTag: "بني",
      },
    },
  ];

  for (const theme of themes) {
    await prisma.theme.upsert({
      where: { slug: theme.slug },
      update: { config: theme.config as unknown as Prisma.InputJsonValue, name: theme.name, nameAr: theme.nameAr, category: theme.category },
      create: {
        slug: theme.slug,
        name: theme.name,
        nameAr: theme.nameAr,
        category: theme.category,
        config: theme.config as unknown as Prisma.InputJsonValue,
        status: ThemeStatus.PUBLISHED,
        createdById: admin.id,
      },
    });
  }

  console.log("Seeded:", {
    admin: admin.phone,
    gateStaff: gateUser.phone,
    plans: plans.length,
    themes: themes.length,
  });
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
